/**
 * Print document builder.
 *
 * Produces a standalone HTML document that honours the global print header
 * settings (organisation lines, logo, document number, page numbers, paper size
 * and orientation) and can be sent to the system print dialog — which also
 * gives a script-complete "Save as PDF" path for Arabic and other scripts the
 * built-in PDF writer cannot embed.
 */
import { escapeXml } from './export/exporters';
import { formatCellValue, type ExportColumn, type Row } from './export/exporters';

export interface PrintHeaderConfig {
  header1: string;
  header2: string;
  header3: string;
  logoDataUrl?: string;
  includeLogo: boolean;
  includeDate: boolean;
  includePageNumbers: boolean;
  docNumberPrefix: string;
  docNumberManual: string;
  docNumberSequence: number;
  orientation: 'portrait' | 'landscape';
  pageSize: 'a4' | 'letter';
  reportTitle: string;
  reportSubtitle: string;
  footerText: string;
  repeatHeaderOnEveryPage: boolean;
}

export const DEFAULT_PRINT_CONFIG: PrintHeaderConfig = {
  header1: 'Text Analysis Manager',
  header2: 'Research Workspace',
  header3: '',
  includeLogo: false,
  includeDate: true,
  includePageNumbers: true,
  docNumberPrefix: 'DOC',
  docNumberManual: '',
  docNumberSequence: 1,
  orientation: 'landscape',
  pageSize: 'a4',
  reportTitle: '',
  reportSubtitle: '',
  footerText: 'Generated by Text Analysis Manager',
  repeatHeaderOnEveryPage: true,
};

export function nextDocumentNumber(config: PrintHeaderConfig): string {
  if (config.docNumberManual.trim()) return config.docNumberManual.trim();
  const stamp = new Date();
  const ymd = `${stamp.getFullYear()}${String(stamp.getMonth() + 1).padStart(2, '0')}${String(stamp.getDate()).padStart(2, '0')}`;
  return `${config.docNumberPrefix || 'DOC'}-${ymd}-${String(config.docNumberSequence).padStart(3, '0')}`;
}

export interface PrintDocumentOptions {
  columns: ExportColumn[];
  rows: Row[];
  config: PrintHeaderConfig;
  title?: string;
  subtitle?: string;
  /** Extra narrative block printed above the table (e.g. a timeline summary). */
  preamble?: string;
}

export function buildPrintDocument(options: PrintDocumentOptions): string {
  const { columns, rows, config } = options;
  const docNumber = nextDocumentNumber(config);
  const size = config.pageSize === 'a4' ? 'A4' : 'Letter';
  const title = options.title ?? config.reportTitle ?? 'Report';
  const subtitle = options.subtitle ?? config.reportSubtitle ?? '';

  const head = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeXml(title)}</title>
<style>
  @page { size: ${size} ${config.orientation}; margin: 16mm 12mm 18mm 12mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Source Sans 3', 'Segoe UI', system-ui, sans-serif; color: #0f172a; font-size: 10.5pt; margin: 0; }
  .sheet { padding: 0; }
  .org { display: flex; align-items: center; gap: 10px; border-bottom: 2px solid #0f766e; padding-bottom: 6px; margin-bottom: 10px; }
  .org img { max-height: 42px; }
  .org .lines { font-size: 9.5pt; color: #334155; line-height: 1.35; }
  h1 { font-size: 16pt; margin: 6px 0 2px; }
  .sub { color: #64748b; font-size: 10pt; margin-bottom: 8px; }
  .meta { display: flex; gap: 16px; font-size: 9pt; color: #475569; margin-bottom: 10px; flex-wrap: wrap; }
  .preamble { font-size: 10pt; color: #334155; margin-bottom: 10px; white-space: pre-wrap; }
  table { border-collapse: collapse; width: 100%; font-size: 9pt; }
  thead { display: table-header-group; }
  th, td { border: 1px solid #cbd5e1; padding: 4px 6px; text-align: start; vertical-align: top; word-break: break-word; }
  th { background: #0f766e; color: #fff; font-weight: 600; }
  tbody tr:nth-child(even) td { background: #f1f5f9; }
  .footer { margin-top: 12px; font-size: 8.5pt; color: #64748b; display: flex; justify-content: space-between; }
  .page-numbers::after { content: "Page " counter(page) " of " counter(pages); }
  @media print { .no-print { display: none !important; } }
</style>
</head>
<body>
<div class="sheet">`;

  const org = `  <div class="org">
${config.includeLogo && config.logoDataUrl ? `    <img src="${config.logoDataUrl}" alt="logo" />\n` : ''}    <div class="lines">
      <div><strong>${escapeXml(config.header1)}</strong></div>
${config.header2 ? `      <div>${escapeXml(config.header2)}</div>\n` : ''}${config.header3 ? `      <div>${escapeXml(config.header3)}</div>\n` : ''}    </div>
  </div>`;

  const meta: string[] = [`${rows.length} records`];
  if (config.includeDate) meta.push(new Date().toISOString().slice(0, 16).replace('T', ' '));
  if (docNumber) meta.push(`Doc ${escapeXml(docNumber)}`);

  const table = `  <table>
    <thead>
      <tr>${columns.map((c) => `<th>${escapeXml(c.label)}</th>`).join('')}</tr>
    </thead>
    <tbody>
${rows
  .map(
    (row) =>
      `      <tr>${columns
        .map((c) => `<td>${escapeXml(formatCellValue(row[c.key], c.format)) || '&nbsp;'}</td>`)
        .join('')}</tr>`,
  )
  .join('\n')}
    </tbody>
  </table>`;

  const footer = `  <div class="footer">
    <span>${escapeXml(config.footerText)}</span>
    ${config.includePageNumbers ? '<span class="page-numbers"></span>' : ''}
  </div>`;

  return `${head}
${org}
  <h1>${escapeXml(title)}</h1>
${subtitle ? `  <div class="sub">${escapeXml(subtitle)}</div>\n` : ''}  <div class="meta">${meta.map((m) => `<span>${m}</span>`).join('')}</div>
${options.preamble ? `  <div class="preamble">${escapeXml(options.preamble)}</div>\n` : ''}${table}
${footer}
</div>
</body>
</html>`;
}

/** Send an HTML document to the system print dialog through a hidden iframe. */
export function printHtml(html: string): boolean {
  if (typeof document === 'undefined') return false;
  const frame = document.createElement('iframe');
  frame.setAttribute('aria-hidden', 'true');
  frame.style.position = 'fixed';
  frame.style.right = '0';
  frame.style.bottom = '0';
  frame.style.width = '0';
  frame.style.height = '0';
  frame.style.border = '0';
  document.body.appendChild(frame);
  const doc = frame.contentDocument;
  if (!doc) {
    frame.remove();
    return false;
  }
  doc.open();
  doc.write(html);
  doc.close();
  const run = () => {
    frame.contentWindow?.focus();
    frame.contentWindow?.print();
    setTimeout(() => frame.remove(), 1500);
  };
  if (doc.readyState === 'complete') setTimeout(run, 100);
  else frame.onload = () => setTimeout(run, 100);
  return true;
}

/** Open the print preview in a new window (useful when the user wants Save as PDF). */
export function openPrintPreview(html: string): boolean {
  if (typeof window === 'undefined') return false;
  const win = window.open('', '_blank', 'noopener,width=1100,height=800');
  if (!win) return false;
  win.document.open();
  win.document.write(html);
  win.document.close();
  return true;
}
